[platformio]
default_envs = nanoatmega328

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
extra_scripts = pre:scripts/generate_board_pins.py
upload_speed = 57600
monitor_speed = 115200
monitor_filters = time, colorize
lib_deps =
  teemuatlut/TMCStepper@^0.7.3
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
