[platformio]
default_envs = nanoatmega328

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
extra_scripts =
  pre:scripts/generate_board_pins.py
  pre:scripts/generate_build_config.py
upload_speed = 57600
monitor_port = COM3
monitor_speed = 115200
monitor_filters = time, colorize, send_on_enter
monitor_echo = yes
monitor_eol = LF
lib_deps =
  teemuatlut/TMCStepper@^0.7.3
